### ISSUE TITLE
Chrome webstore release stuck at 1.8.15

### ISSUE THREAD

**Issue by mikeydevelops** [material-extensions/material-icons-browser-extension#109] opened 2024-07-20 18:48 UTC
It appears the extension stopped releasing on chrome web store. Extension page says version 1.8.15.

![image](https://github.com/user-attachments/assets/e4151dcc-21e4-4938-abf8-3189aa54051e)

I see 3 latest actions failed, maybe it is connected to that. Interesting thing, version on Microsoft Edge Add-on store is 1.8.16 and on Firefox add-ons it is the latest at 1.8.18.

**Comment by PKief** [comment] 2024-07-22 13:59
Firefox works the most reliably of the three browsers. I'm not sure what the problem is with Chrome and Edge. @shivapoudel would you mind checking it again, what happened with the Edge addon? @Claudiohbsantos maybe you can have a look at it once you are available for the Chrome browser. Seems like the latest versions are stuck in some review processes.

**Comment by mikeydevelops** [comment] 2024-07-22 14:50
@PKief Since you took on maintaining the extension, I propose @Claudiohbsantos and @shivapoudel transfer the extension to your respective platform accounts. That way, problems like this will be fixed on your timetable instead of waiting until someone is free to maybe write a message, test once, then wait for answer and so on..

**Comment by Claudiohbsantos** [comment] 2024-07-23 16:03
Yeah, agreed on that, we shouldn't have a bottleneck for releases on a single person. I'm looking into that now, at least for the chrome extension it's looking like a simple path forward.

Regarding the current issue, it just needs some manual updates due to the new `scripting` permissions added to the manifest for the [custom domain](https://github.com/material-extensions/material-icons-browser-extension/pull/85) functionality. I am pushing the changes now and expect the new version to be published soon after when it goes through their review process

**Comment by Claudiohbsantos** [comment] 2024-07-25 14:13
The manual updates worked and the chrome store currently lists version 1.8.19 so I'm going to close this issue as resolved. Thanks for flagging!

**Closed by Claudiohbsantos** 2024-07-25 14:13 UTC
